"""empty message

Revision ID: 93d4d876bd50
Revises: 
Create Date: 2021-01-26 12:48:59.096793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93d4d876bd50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('independent', sa.String(), nullable=True),
    sa.Column('dependent', sa.String(), nullable=True),
    sa.Column('data_set', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('linear_coefficients', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('linear_error', sa.Float(), nullable=True),
    sa.Column('quadratic_coefficients', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('quadratic_error', sa.Float(), nullable=True),
    sa.Column('cubic_coefficients', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('cubic_error', sa.Float(), nullable=True),
    sa.Column('hyperbolic_coefficients', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('hyperbolic_error', sa.Float(), nullable=True),
    sa.Column('exponential_coefficients', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('exponential_error', sa.Float(), nullable=True),
    sa.Column('logarithmic_coefficients', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('logarithmic_error', sa.Float(), nullable=True),
    sa.Column('best_fit', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regressions')
    op.drop_table('users')
    # ### end Alembic commands ###
